name = "vote-thumbnail"
pages_build_output_dir = "public"
compatibility_date = "2025-01-01"

[vars]
ALLOWED_ORIGIN = "https://vote-thumbnail.pages.dev"
DEMO_FILL = "0" # 1:ダミーピンを有効化 0: 無効

# D1 データベース
[[d1_databases]]
binding = "DB"
database_name = "vote-thumbnail"
database_id = "2f52ba87-bf70-4394-add3-1e0a7676d430"

# KV (レート制限・一時BAN用)
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "21669d61452d4dd58ae9bf7294c71a5d"
